dist: bionic
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
cache: npm
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: Release
      node_js: "8"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
