sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
  webhooks: https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}
node_js:
  - '8'
  - '6'
  - '4'
after_success:
  # custom travis_after_all script under @remy's private gist
  - 'curl -Lo travis_after_all.py https://git.io/vzaBe'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
